### ISSUE TITLE
ARM architecture is not considered.

### ISSUE THREAD

**Issue by dedalusj** [kevva/bin-wrapper#11]
In the `_parse` function on line 189 only the `x64` and `x86` architectures are currently considered.

I was recently trying to install `node-pngquant-bin` on `arm` machine but it fails because of the lack of support for the architecture. I forked the `node-pngquant-bin` repository, compiled the binary for the `arm` platform and included it in the repository but the lack of support for the architecture in `bin-wrapper` means that the `x86` is always downloaded.

**Comment by shubhamjain** [comment]
This issue is not fixed. Or has been broken since use of os-filter-obj, which use arch, which only returns x64 or x86. I fail to understand the obsession with creating needless dependencies, breaking what's working once.
