### ISSUE TITLE
Install error `Cannot find module`.

### ISSUE THREAD

**Issue by k-kinzal** [kevva/bin-wrapper#40]
https://travis-ci.org/k-kinzal/failed-bin-wrapper-/jobs/73195061#L101-L143
I found install error.

https://github.com/k-kinzal/failed-bin-wrapper-/blob/master/package.json#L6-L7
If you use the same dependent module in the parent and child , postinstall will start in before the installation is complete.
Install error is likely to occur and dependencies of the dependent module is large.

**Comment by shinnn** [comment]
Should be correctly handled by `npm`. https://github.com/npm/npm/issues
