### ISSUE TITLE
prefer to use system binary if available

### ISSUE THREAD

**Issue by torvitas** [kevva/bin-wrapper#50]
Hi,

it were nice if bin wrapper would just use the systems binaries if available. This especially makes sense for alpine Linux where static compiled binaries often do not work.

Greetings, Sascha

**Comment by eshion** [comment]
+1

**Comment by perrin4869** [comment]
+1

**Comment by ri0t** [comment]
This has quite substantial (_positive_) consequences for **arm64** and other platforms, imho. I strongly advise to add this functionality. There are some problems other people already mentioned, though:

Among them the possibility of many varying versions of binary packages, maybe restrictions on which versions would be available (e.g. on [Debian](https://packages.debian.org/search?keywords=optipng&searchon=names&exact=1&suite=all&section=all)).

Then again, i see this issue has last been touched _end of 2017_. Is this thing still on?
If so, cheers! :champagne: :cake:

**Comment by torvitas** [comment]
Hi, I do not have any interest in this issue anymore, I wrote some code back then which is available as pull-request. Beware that this code still has issues that need to be solved which is why it never was merged.
