### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Ilshidur** [kevva/bin-wrapper#55]
Some dependencies of the version 3.0.2 [are vulnerable](https://snyk.io/test/npm/bin-wrapper/3.0.2). It would be nice to update them.

Or at least (in _package.json_) :
`"download": "^4.0.0"` to `"download": "^5.0.1"` because _4.4.3_ [is vulnerable](https://snyk.io/test/npm/download/4.4.3) and _5.0.1_ [fixed it](https://snyk.io/test/npm/download/5.0.1).

The better would be to update `"download": "^4.0.0"` to `"download": "^6.2.5"` (the latest version released).

I can open a PR in case you don't have the time.

***

EDIT : Seems to be fixed [here](https://github.com/kevva/bin-wrapper/commit/ae463541d3c906aa7972c81732fbda82c3c6456c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32).

**Comment by Ilshidur** [comment]
Is it possible to merge the branch `listr` ? As it contains the fix for this issue, it would be nice to publish it to npm if this is production ready :+1: 

Otherwise, I can open a PR with an update of `package.json` :-)

**Comment by benmurden** [comment]
This is now also causing a deprecation warning for `gulp-util`, which the older `download` still used.

Unfortunately, it looks like the API has been changed in this branch, and is incompatible with the libraries I tried. They would have to be updated, too.

**Comment by rejas** [comment]
PR for this is in https://github.com/kevva/bin-wrapper/pull/65
